### PR TITLE
Some minor tweaks for nodebb 1.6.0

### PR DESCRIPTION
**Pull request by jmooradi**

### CODE REVIEW

**Comment by pichalite** [comment]
@jmooradi this theme is not based on persona. No need to set base theme.

**Comment by jmooradi** [comment]
I had an template not found issue a while ago that caused issues, isn't it safer to set the nodebb default theme as a base theme?

Also the extra endif breaks profile pages on 1.6.0

**Comment by pichalite** [comment]
> isn't it safer to set the nodebb default theme as a base theme?
Not really. NodeBB already does that anyway in core.

Extra endif fix is fine. Just remove the base theme change and I will merge the PR.

**Comment by jmooradi** [comment]
done :)

**Comment by jmooradi** [comment]
Removing base template causes the following error:
Unable to load template: partials/category-selector

**Comment by pichalite** [comment]
@jmooradi It's just a warning not an error. You will see the warning but NodeBB picks up the template from persona. The theme is not updated for NodeBB v1.6.0 yet. You will have to wait for it to be updated.

**Comment by barisusakli** [comment]
+1 without this the profile page does not render anything if the user has uploaded a picture

**Pull request merged**
