### PR TITLE
Add plugin custom settings block to profile.

### PR DESCRIPTION
**Pull request by yariplus**

### CODE REVIEW

**Comment by pichalite** [comment]
@yariplus I think custom settings should be at the end after core settings (not some where in the middle) so, move the block to the end after the language section.

Also remove the commit for package version change. I will make that after the PR merge.

**Comment by yariplus** [comment]
np, done!

**Comment by pichalite** [comment]
Thanks @yariplus

**Comment by kubaboski** [comment]
Hey, also the social connect is not showing up in your theme :/

**Pull request merged**
